/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Drol
 */
public class DecodeView extends javax.swing.JFrame {

    /**
     * Creates new form EncodeView
     */
    public DecodeView() {
        initComponents();
        this.setVisible(true);
    }

    public void setSecretText(String txt) {
        jTextFieldSecreteText.setText(txt);
    }

    public void addMouseActionSecretText(MouseAdapter ma) {
        jTextFieldSecreteText.addMouseListener(ma);
    }

    public void displayError(String error) {
        JOptionPane.showMessageDialog(null, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void addActionListenerShowHiddenMessage(ActionListener al) {
        jButtonShowHiddenMessage.addActionListener(al);
    }

    public void addActionListenerQuit(ActionListener al) {
        jButtonQuit.addActionListener(al);
    }

    public void addActionListenerBrowseImage(ActionListener al) {
        jButtonBrowseImage.addActionListener(al);
    }

    public String getStegoImagePath() {
        return jTextFieldStegoImageFile.getText();
    }

    public void setStegoImagePath(String path) {
        jTextFieldStegoImageFile.setText(path);
    }

    public void setSecretMessage(String msg) {
        jTextFieldSecreteText.setText(msg);
    }

    public void exitDecode() {
        this.dispose();
    }

    public void setStegoImage(ImageIcon imageIcon) {
        jLabelShowStegoImage.setIcon(imageIcon);
    }

    public void displayNotify(String txt) {
        JOptionPane.showMessageDialog(null, txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIntroduce = new javax.swing.JLabel();
        jLabelSecreteText = new javax.swing.JLabel();
        jTextFieldSecreteText = new javax.swing.JTextField();
        jLabelStegoImageFile = new javax.swing.JLabel();
        jTextFieldStegoImageFile = new javax.swing.JTextField();
        jButtonBrowseImage = new javax.swing.JButton();
        jLabelStegoImage = new javax.swing.JLabel();
        jButtonShowHiddenMessage = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();
        jScrollPaneStegoImage = new javax.swing.JScrollPane();
        jLabelShowStegoImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LSB Substitution - Enscypt");

        jLabelIntroduce.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelIntroduce.setText("Getting data from Stego-image");

        jLabelSecreteText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSecreteText.setText("Secret text:");

        jTextFieldSecreteText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSecreteText.setText("<<a secrete message>>");

        jLabelStegoImageFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelStegoImageFile.setText("Stego-image file:");

        jTextFieldStegoImageFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonBrowseImage.setText("Browse");

        jLabelStegoImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStegoImage.setText("Stego-image");

        jButtonShowHiddenMessage.setText("Show the hidden message");

        jButtonQuit.setText("Quit");

        jScrollPaneStegoImage.setViewportView(jLabelShowStegoImage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIntroduce)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelStegoImage)
                            .addGap(635, 635, 635))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSecreteText)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSecreteText, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStegoImageFile)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldStegoImageFile, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonBrowseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonQuit)))))
                    .addComponent(jButtonShowHiddenMessage))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelIntroduce)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBrowseImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelStegoImageFile)
                        .addComponent(jTextFieldStegoImageFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelStegoImage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonShowHiddenMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSecreteText)
                    .addComponent(jTextFieldSecreteText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonQuit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelSecreteText, jLabelStegoImageFile, jTextFieldSecreteText, jTextFieldStegoImageFile});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonShowHiddenMessage;
    private javax.swing.JLabel jLabelIntroduce;
    private javax.swing.JLabel jLabelSecreteText;
    private javax.swing.JLabel jLabelShowStegoImage;
    private javax.swing.JLabel jLabelStegoImage;
    private javax.swing.JLabel jLabelStegoImageFile;
    private javax.swing.JScrollPane jScrollPaneStegoImage;
    private javax.swing.JTextField jTextFieldSecreteText;
    private javax.swing.JTextField jTextFieldStegoImageFile;
    // End of variables declaration//GEN-END:variables
}
