/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Drol
 */
public class EncodeView extends javax.swing.JFrame {

    /**
     * Creates new form EncodeView
     */
    public EncodeView() {
        initComponents();
        this.setVisible(true);
    }

    public void setSecretMessage(String txt) {
        jTextFieldSecreteText.setText(txt);
    }

    public void addMouseActionSecretText(MouseAdapter ma) {
        jTextFieldSecreteText.addMouseListener(ma);
    }

    public void exitProgram() {
        this.dispose();
    }

    public void displayError(String error) {
        JOptionPane.showMessageDialog(null, error, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    public void displayMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public void addActionListenerHideMessage(ActionListener al) {
        jButtonHideMessage.addActionListener(al);
    }

    public void addActionListenerQuit(ActionListener al) {
        jButtonQuit.addActionListener(al);
    }

    public void addActionListenerSaveStego(ActionListener al) {
        jButtonSaveStego.addActionListener(al);
    }

    public void addActionListenerBrowseImage(ActionListener al) {
        jButtonBrowseImage.addActionListener(al);
    }

    public String getSecretMessage() {
        return jTextFieldSecreteText.getText();
    }

    public String getOriginalImagePath() {
        return jTextFieldOriginalImageFile.getText();
    }

    public void setOriginalImage(ImageIcon imageIcon) {
        jLabelShowOriginalImage.setIcon(imageIcon);
    }

    public void setStegoImage(ImageIcon imageIcon) {
        jLabelShowStegoImage.setIcon(imageIcon);
    }

    public int getjScrollPanelOriginalImageWidth() {
        return jScrollPaneOriginalImage.getWidth();
    }

    public int getjScrollPanelOriginalImageHeight() {
        return jScrollPaneOriginalImage.getHeight();
    }

    public void setOriginalImagePath(String path) {
        jTextFieldOriginalImageFile.setText(path);
    }

    public int displayConfirm(String txt) {
        return JOptionPane.showConfirmDialog(null, txt);
    }

    public int getHeightContainerOriImage() {
        return jLabelShowOriginalImage.getHeight();
    }

    public int getHeightContainerStegoImage() {
        return jLabelShowStegoImage.getHeight();
    }

    public int getWidthContainerOriImage() {
        return jLabelShowOriginalImage.getWidth();
    }

    public int getWidthContainerStegoImage() {
        return jLabelShowStegoImage.getWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIntroduce = new javax.swing.JLabel();
        jLabelSecreteText = new javax.swing.JLabel();
        jTextFieldSecreteText = new javax.swing.JTextField();
        jLabelOriginalImageFile = new javax.swing.JLabel();
        jTextFieldOriginalImageFile = new javax.swing.JTextField();
        jButtonBrowseImage = new javax.swing.JButton();
        jLabelOriginalImage = new javax.swing.JLabel();
        jLabelStegoImage = new javax.swing.JLabel();
        jButtonHideMessage = new javax.swing.JButton();
        jButtonSaveStego = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();
        jScrollPaneOriginalImage = new javax.swing.JScrollPane();
        jLabelShowOriginalImage = new javax.swing.JLabel();
        jScrollPaneStegoImage = new javax.swing.JScrollPane();
        jLabelShowStegoImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LSB Substitution - Enscypt");
        setResizable(false);

        jLabelIntroduce.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelIntroduce.setText("Hiding data in image using LSB Substitution");

        jLabelSecreteText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSecreteText.setText("Secret text:");

        jTextFieldSecreteText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSecreteText.setText("<<a secrete message>>");

        jLabelOriginalImageFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelOriginalImageFile.setText("Original image file");

        jTextFieldOriginalImageFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonBrowseImage.setText("Browse");

        jLabelOriginalImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOriginalImage.setText("OriginalImage");

        jLabelStegoImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelStegoImage.setText("Stego-Image");

        jButtonHideMessage.setText("Hide the message");

        jButtonSaveStego.setText("Save Stego-Image");

        jButtonQuit.setText("Quit");

        jScrollPaneOriginalImage.setViewportView(jLabelShowOriginalImage);

        jScrollPaneStegoImage.setViewportView(jLabelShowStegoImage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHideMessage)
                    .addComponent(jLabelIntroduce)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSecreteText)
                                .addComponent(jLabelOriginalImageFile))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldSecreteText, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldOriginalImageFile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonBrowseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelOriginalImage)
                                .addComponent(jScrollPaneOriginalImage, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelStegoImage)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonSaveStego)
                                            .addGap(188, 188, 188)
                                            .addComponent(jButtonQuit))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPaneStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(14, 14, 14))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonHideMessage, jButtonSaveStego});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPaneOriginalImage, jScrollPaneStegoImage});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelIntroduce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSecreteText)
                    .addComponent(jTextFieldSecreteText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBrowseImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelOriginalImageFile)
                        .addComponent(jTextFieldOriginalImageFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOriginalImage)
                    .addComponent(jLabelStegoImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneOriginalImage, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHideMessage)
                            .addComponent(jButtonSaveStego)
                            .addComponent(jButtonQuit)))
                    .addComponent(jScrollPaneStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelOriginalImageFile, jLabelSecreteText, jTextFieldOriginalImageFile, jTextFieldSecreteText});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonHideMessage, jButtonSaveStego});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPaneOriginalImage, jScrollPaneStegoImage});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonHideMessage;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonSaveStego;
    private javax.swing.JLabel jLabelIntroduce;
    private javax.swing.JLabel jLabelOriginalImage;
    private javax.swing.JLabel jLabelOriginalImageFile;
    private javax.swing.JLabel jLabelSecreteText;
    private javax.swing.JLabel jLabelShowOriginalImage;
    private javax.swing.JLabel jLabelShowStegoImage;
    private javax.swing.JLabel jLabelStegoImage;
    private javax.swing.JScrollPane jScrollPaneOriginalImage;
    private javax.swing.JScrollPane jScrollPaneStegoImage;
    private javax.swing.JTextField jTextFieldOriginalImageFile;
    private javax.swing.JTextField jTextFieldSecreteText;
    // End of variables declaration//GEN-END:variables
}
